[package]
name = "axumbackend"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.43", features = ["serde"] }
dotenvy = "0.15"
parking_lot = { version = "0.12.5", features = ["serde"] }
axum = "0.7.5"
axum-extra = { version = "0.9.3", features = ["typed-routing"] }
tower-http = { version = "0.5.2", features = ["cors"] }
tokio = { version = "1.0", features = ["full"] }
tokio-postgres = { version = "0.7.12" }
postgres-types = { version = "0.2.9", features = ["with-chrono-0_4", "with-uuid-1"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
uuid = { version = "1.11.0", features = ["v4", "serde"] }
